### ISSUE TITLE
Why some of the files are missing

### ISSUE THREAD

**Issue by modimobeikete** [fedddddd/h2-zonetool#90]
Here is a problem.I try to use virtual studio to pack a exe files.But when I started building.There's a lot error missing.Like unable to open included files.They said no such file or directory.Is these files are generated or actually in the source files?
![QQ截图20221206120112](https://user-images.githubusercontent.com/54436686/205810076-a06acb5d-d0d1-4a09-b241-bbe01e7be15d.png)

**Comment by VladWinner** [comment]
![Screenshot_20221206_201455](https://user-images.githubusercontent.com/13555921/205978247-989b840c-22bf-4e38-8f66-15be322480aa.jpg)
